catalog/urls.py
from django.urls import path
from catalog import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

#已借
urlpatterns += [
    #path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('mybooks/', views.mybooks, name='my-borrowed'),
    path('borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
]

#续借
urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]

# Use static() to add url mapping to serve static files during development (only)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Use include() to add URLS from the catalog application and authentication system

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from distutils.command.upload import upload
from email.mime import image
from email.policy import default
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User
from datetime import date
import uuid # Required for unique book instances
# Create your models here.

# 书籍类别模型
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

# 书籍模型
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    isbn = models.CharField('ISBN', max_length=13, null=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    imprint = models.CharField(max_length=200,null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    image = models.ImageField(upload_to='book',default='book/default.jpg')

    class Meta:
        ordering = ['title', 'imprint']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.title} {self.imprint}'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    
    display_genre.short_description = 'Genre'


# 书籍模型（具体的某一本书）

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', '保存'),#Maintenance
        ('o', '借出'),#On loan
        ('a', '可借'),#Available
        ('r', '预约'),#Reserved
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned","Set book as returned"), ("renew_due_back", "renew return date"))

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.book.title} {self.book.imprint}'


    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


# 作者模型
class Author(models.Model):
    """Model representing an author."""
    # first_name = models.CharField(max_length=100)
    # last_name = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    image = models.ImageField(upload_to='author',default='author/default.jpg')
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the author',default="暂无简介")

    sex_list = (
        ('F','女'),
        ('M','男'),
        ('O','其他')
    )

    sex = models.CharField(
        max_length=1,
        choices=sex_list,
        blank=True,
        default='M',
        help_text='性别',
    )    
    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def get_sex(self):
        if self.sex=='F':
            return '女'
        elif self.sex=='M':
            return '男'
        else:
            return '其他'

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'

catalog/forms.py
#表单相关
from django import forms

from django.core.exceptions import ValidationError
# 低版本django，高版本不支持
# from django.utils.translation import ugettext_lazy as _
import datetime 

# 续借
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="输入续借后的归还日期(限制在4周内，默认为3周).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #检查输入
        if data < datetime.date.today():
            raise ValidationError('无效日期 - 不能输入过去的日期')

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError('无效日期 - 续借超出4周')

        return data

catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Book, Author, BookInstance, Genre

from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.decorators import permission_required

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

from .forms import RenewBookForm

from django.contrib.auth.decorators import login_required 

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # The 'all()' is implied by default.

    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors,'num_visits':num_visits},
    )

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksAllListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

# 续借
@login_required
@permission_required('catalog.renew_due_back')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst=get_object_or_404(BookInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

"""
class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').filter(borrower=self.request.user).order_by('due_back')
"""

#还书
@login_required
def mybooks(request):
    bookinst_list=BookInstance.objects.filter(status__exact='o').filter(borrower=request.user).order_by('due_back')
    if request.method == 'POST':
        bookinst_id=request.POST.get("bookinst_id")
        bookinst=BookInstance.objects.filter(id=bookinst_id)
        bookinst.update(status='a')
    return render(
        request,
        'catalog/bookinstance_list_borrowed_user.html',
        {'bookinstance_list':bookinst_list},
    )

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-fluid">
  <h1>{{ author }} </h1>
  <div class="media">
    <div class="media-left">
      <img src="{{ MEDIA_URL }}{{ author.image }}" alt="作者照片", width="200px" height="270px">
    </div>          
    <div class="media-body">
      <p>性别：{{ author.get_sex }}</p>
      <p>
        {% if author.date_of_death %}
        生卒日期：{{author.date_of_birth}}至{{author.date_of_death}}
        {% else %}
        出生日期：{{author.date_of_birth}}
        {% endif %}
      </p>
    </div>
  </div>
  <div style="margin-top:30px">
    <h4>作者简介</h4>
    <p>{{ author.summary }}</p>
  </div>


  <div style="margin-top:30px">
    <h4>相关图书</h4>

    <ul class="list-group">
      {% for book in author.book_set.all %}
      <li class="list-group-item">
        <div class="media">
          <!--
          <div class="media-left media-middle">
            <img class="media-object" src="{{ MEDIA_URL }}{{ book.image }}" alt="图书封面" width="60px" height="80px">
          </div>          
          -->
          <div class="media-body">
            <h4 class="list-group-item-heading">
              <a href="{% url 'book-detail' book.pk %}">{{book}}</a> (馆藏数量：{{book.bookinstance_set.all.count}})
            </h4>
            <p class="list-group-item-text">{{book.summary}}</p>
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>    
  </div>
</div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-fluid">
  <h1>作者列表</h1>

  {% if author_list %}
    <ul class="list-group">

    {% for author in author_list %}
      <li class="list-group-item">
        <div class="media">
          <div class="media-left media-middle ">
            <img class="media-object" src="{{ MEDIA_URL }}{{ author.image }}" alt="作者照片" width="60px" height="80px">
          </div>
          <div class="media-body">
            <a href="{{ author.get_absolute_url }}">
              <h4 class="list-group-item-heading">{{ author.name }}</h4>
            </a>
            <p class="list-group-item-text">
              {% if author.date_of_death %}
              生卒日期：{{author.date_of_birth}}至{{author.date_of_death}}
              {% else %}
              出生日期：{{author.date_of_birth}}
              {% endif %}
            </p>
          </div>
        </div>
      </li>      
    {% endfor %}

  </ul>
  {% else %}
    <p>暂时没有收录作者信息</p>
  {% endif %}  
</div>

        
        
        
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<div class="container-fluid">
  <!--
    <p>类型: {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>     
  -->
  <h1>{{ book.title }}</h1>
  <div class="media">
    <div class="media-left">
      <img src="{{ MEDIA_URL }}{{ book.image }}" alt="图书封面", width="200px" height="270px">
    </div>          
    <div class="media-body">
      <p>作者: <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> 
      <p>出版信息: {{ book.imprint }}</p>
      <p>ISBN: {{ book.isbn }}</p>
    </div>
  </div>

  <div style="margin-top:30px">
    <h4>图书简介</h4>
    <p>{{ book.summary }}</p>
  </div>  
 
  <div style="margin-top:30px">
    <h4 style="margin-bottom:20px">馆藏</h4>
    {% for copy in book.bookinstance_set.all %}
    <!--
      class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}"
    -->
    <p>状态：{{ copy.get_status_display }}</p>
    {% if copy.status == 'o' %}
      <p>应还日期 {{copy.due_back}}</p>
    {% endif %}
    <p class="text-muted">id：{{copy.id}}</p>
    <hr>

    {% endfor %}
  </div>
</div>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="container-fluid">
    <h1>图书列表</h1>

    {% if book_list %}
    <ul class="list-group">

      {% for book in book_list %}
      <li class="list-group-item">
        <div class="media">
          <div class="media-left media-middle">
            <img class="media-object" src="{{ MEDIA_URL }}{{ book.image }}" alt="图书封面" width="60px" height="80px">
          </div>
          <div class="media-body">
            <a href="{{ book.get_absolute_url }}">
              <h4 class="list-group-item-heading">{{ book.title }}</h4>
            </a>
            <p class="list-group-item-text">作者：{{book.author}}<br>出版信息：{{ book.imprint }}</p>
          </div>
        </div>
      </li>          
      {% endfor %}

    </ul>
    {% else %}
      <p>图书馆内暂时还没有图书</p>
    {% endif %}    
  </div>

{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <div div class="container-fluid">
        <h1>续借</h1>
        <p>书名：{{bookinst.book.title}}</p>
        <p>出版信息：{{bookinst.book.imprint}}</p>
        <p>复本ID：{{ bookinst.id }}</p>
        <p>借书人: {{bookinst.borrower}}</p>
        <p {% if bookinst.is_overdue %} class="text-danger"{% endif %}>应还期限: {{bookinst.due_back}}</p>
    </div>
   
    <form action="" method="post">
        {% csrf_token %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-1"><label>新的归还期限</label></div>
                <div class="col-md-2">
                    <div>{{ form.renewal_date}}</div>
                    <div>{{ form.renewal_date.help_text}}</div>
                </div>
                <div class="col-md-1"><input type="submit" value="Submit"></div>
            </div>               
        </div>
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}

<div class="container-fluid">
  <h1>外借图书</h1>

  {% if bookinstance_list %}
  <ul class="list-group" >

    {% for bookinst in bookinstance_list %}
    <li class="list-group-item">
      <div class="media">
        <div class="media-body {% if bookinst.is_overdue %}text-danger{% endif %}">
          <h4 class="list-group-item-heading">{{bookinst.book.title}}</h4>
          <p class="list-group-item-text">借书人：{{ bookinst.borrower }}</p>
          <p class="list-group-item-text">应还期限：{{ bookinst.due_back }}</p>
          <p class="list-group-item-text">复本ID：{{ bookinst.id }}</p>
        </div>
        <div class="media-right media-middle">
          <a href="{% url 'renew-book-librarian' bookinst.id %}"><button type="button" class="btn btn-success">续借</button></a>
        </div>
      </div>
    </li>

    {% endfor %}
  </ul>

  {% else %}
    <p>暂时没有图书外借</p>
  {% endif %}  
</div>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}


<div class="container-fluid">

  <h1>借阅书目</h1>

  {% if bookinstance_list %}
  <ul class="list-group">
    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %} list-group-item">
      <div class="media">
        <div  class="media-body">
            <h4 class="list-group-item-heading">
              <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
            </h4>
            <p class="list-group-item-text">应还期限：{{ bookinst.due_back }}</p>     
        </div>
        <div class="media-right media-middle">
          {% if bookinst.is_overdue %}
            <button class="btn btn-danger disabled">逾期</button>
          {% else %}
            <form action="" method="post">
            {% csrf_token %}
              <input hidden name="bookinst_id" value="{{ bookinst.id }}">
              <input class="btn btn-success" type="submit" value="还书">
              <!--<button class="btn btn-success" id="return_book">还书</button>-->   
            </form>
          {% endif %}
        </div>    
      </div>
    </li>       

    {% endfor %}
  </ul>

  {% else %}
    <p>未查询到借阅信息</p>
  {% endif %}  
</div>

{% endblock %}